# Generated by Django 4.2 on 2023-05-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Video',
        ),
    ]
