# Generated by Django 4.2 on 2023-05-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_item_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Item',
        ),
    ]
